name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - development

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore OsuStocks.sln

      - name: Build
        run: dotnet build OsuStocks.sln --no-restore -c Release

      - name: Run Unit Tests
        run: dotnet test tests/OsuStocks.Application.UnitTests/OsuStocks.Application.UnitTests.csproj --no-build -c Release

      - name: Run Postgres Testcontainers Integration Tests
        run: dotnet test tests/OsuStocks.Api.IntegrationTests/OsuStocks.Api.IntegrationTests.csproj --no-build -c Release --filter "WalletEndpointsTests|TradingEndpointsTests|PortfolioEndpointsTests|MarketEngineIntegrationTests"
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
